[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

bold = { family = "RobotoMono Nerd Font", style = "Bold" }

italic = { family = "RobotoMono Nerd Font", style = "Italic" }

size = 10

[colors.primary]
background = "#fff5ff"
foreground = "#4a3549"
